# Data Cleaning

This notebook focuses on assessing and improving the quality of the datasets before performing exploratory data analysis.

The objectives are:

- Load all datasets
- Assess data quality
- Identify potential issues
- Clean the data where necessary
- Save cleaned datasets for further analysis

## 1. Import Libraries

In [2]:
import pandas as pd
import numpy as np

from pathlib import Path

## 2. Load Datasets

In [3]:
DATA_DIR = Path("C:\\Users\\User\\OneDrive\\Desktop\\premium_nexus_task\\data\\raw")

sales = pd.read_csv(DATA_DIR / "sales_transaction.csv")
sales_line = pd.read_csv(DATA_DIR / "sales_transactionline.csv")
products = pd.read_csv(DATA_DIR / "product_master.csv")
customers = pd.read_csv(DATA_DIR / "customers.csv")
branches = pd.read_csv(DATA_DIR / "branch_master.csv")
inventory = pd.read_csv(DATA_DIR / "inventory_daily.csv")
survey = pd.read_csv(DATA_DIR / "survey_feedback.csv")

## 3. Organize Datasets

In [4]:
datasets = {
    "Sales": sales,
    "Sales Line": sales_line,
    "Products": products,
    "Customers": customers,
    "Branches": branches,
    "Inventory": inventory,
    "Survey": survey,
}

## 4. Dataset Overview

In [5]:
overview = pd.DataFrame(
    [
        {
            "Dataset": name,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
        }
        for name, df in datasets.items()
    ]
)

overview

      Dataset   Rows  Columns
0       Sales   5129        7
1  Sales Line  12914        7
2    Products     18        7
3   Customers    120        6
4    Branches      6        4
5   Inventory   4320        6
6      Survey    900        9

## 5. Structure Inspection

In [6]:
for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print("=" * 70)

    print(f"Shape: {df.shape}")
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\n")

======================================================================
Sales
======================================================================
Shape: (5129, 7)

Columns:
['transaction_id', 'transaction_ts', 'sales_date', 'branch_id', 'customer_id', 'payment_method', 'basket_amount']

Data Types:
transaction_id    object
transaction_ts    object
sales_date        object
branch_id         object
customer_id       object
payment_method    object
basket_amount      int64
dtype: object

First 5 Rows:

,transaction_id,transaction_ts,sales_date,branch_id,customer_id,payment_method,basket_amount
0,T0000001,2025-01-01 10:34:15,2025-01-01,B02,C0086,cash,7200
1,T0000002,2025-01-01 18:31:46,2025-01-01,B01,C0026,wallet,14300
2,T0000003,2025-01-01 11:05:56,2025-01-01,B02,C0039,card,4800
3,T0000004,2025-01-01 07:02:00,2025-01-01,B05,NaN,card,18700
4,T0000005,2025-01-01 07:44:34,2025-01-01,B04,C0055,wallet,19800

======================================================================
Sales Line
======================================================================
Shape: (12914, 7)

Columns:
['line_id', 'transaction_id', 'product_code', 'qty', 'unit_price', 'discount_amt', 'line_amount']

Data Types:
line_id           object
transaction_id    object
product_code      object
qty                int64
unit_price         int64
discount_amt       int64
line_amount        int64
dtype: object

First 5 Rows:

,line_id,transaction_id,product_code,qty,unit_price,discount_amt,line_amount
0,L00000001,T0000001,BEV003,1,4000,200,3800
1,L00000002,T0000001,DES003,1,3700,300,3400
2,L00000003,T0000002,BEV002,1,1600,300,1300
3,L00000004,T0000002,DES003,1,3500,300,3200
4,L00000005,T0000002,BEV003,1,4200,300,3900

======================================================================
Products
======================================================================
Shape: (18, 7)

Columns:
['product_code', 'product_name', 'category_code', 'category_name', 'base_price', 'brand_type', 'margin_band']

Data Types:
product_code     object
product_name     object
category_code    object
category_name    object
base_price        int64
brand_type       object
margin_band      object
dtype: object

First 5 Rows:

,product_code,product_name,category_code,category_name,base_price,brand_type,margin_band
0,SNK001,Potato Chips Sea Salt,SNK,Snacks,3800,Import,A
1,SNK002,Corn Chips Spicy,SNK,Snacks,4200,Import,C
2,SNK003,Protein Bar,SNK,Snacks,5200,Local,A
3,SNK004,Chocolate Wafer,SNK,Snacks,2800,Local,B
4,BEV001,Cola 500ml,BEV,Beverage,2500,Local,C

======================================================================
Customers
======================================================================
Shape: (120, 6)

Columns:
['customer_id', 'join_date', 'seed_segment', 'gender', 'age', 'loyalty_channel']

Data Types:
customer_id        object
join_date          object
seed_segment       object
gender             object
age                 int64
loyalty_channel    object
dtype: object

First 5 Rows:

  customer_id   join_date          seed_segment gender  age loyalty_channel
0       C0001  2024-05-31      Morning commuter      F   41             App
1       C0002  2023-05-22      Morning commuter      F   31            Card
2       C0003  2023-06-07  Student value seeker      M   47     Cash-linked
3       C0004  2023-08-26       Family stock-up      M   33             App
4       C0005  2024-03-28      Morning commuter      M   51            Card

======================================================================
Branches
======================================================================
Shape: (6, 4)

Columns:
['branch_id', 'branch_name', 'zone', 'store_size']

Data Types:
branch_id      object
branch_name    object
zone           object
store_size     object
dtype: object

First 5 Rows:

  branch_id branch_name              zone store_size
0       B01    Branch 1          Downtown     Medium
1       B02    Branch 2   Office district     Medium
2       B03    Branch 3  Residential east      Small
3       B04    Branch 4  Residential west      Small
4       B05    Branch 5        University      Small

======================================================================
Inventory
======================================================================
Shape: (4320, 6)

Columns:
['inventory_date', 'branch_id', 'product_code', 'on_hand_qty', 'reorder_point', 'stock_flag']

Data Types:
inventory_date    object
branch_id         object
product_code      object
on_hand_qty        int64
reorder_point      int64
stock_flag        object
dtype: object

First 5 Rows:

  inventory_date branch_id product_code  on_hand_qty  reorder_point stock_flag
0     2025-01-01       B01       SNK004           29             36         OK
1     2025-01-01       B01       DES003           22             26        LOW
2     2025-01-01       B01       SNK002            1              5        OOS
3     2025-01-01       B01       SNK003           11             18         OK
4     2025-01-01       B01       SNK001           14             20         OK

======================================================================
Survey
======================================================================
Shape: (900, 9)

Columns:
['feedback_id', 'feedback_date', 'branch_id', 'product_code', 'quality_score', 'visual_score', 'would_buy_again', 'what_to_improve', 'general_thoughts']

Data Types:
feedback_id         object
feedback_date       object
branch_id           object
product_code        object
quality_score        int64
visual_score         int64
would_buy_again     object
what_to_improve     object
general_thoughts    object
dtype: object

First 5 Rows:

,feedback_id,feedback_date,branch_id,product_code,quality_score,visual_score,would_buy_again,what_to_improve,general_thoughts
0,F00001,2025-01-27,B01,RTE002,7,7,yes,bundle with drink,liked the freshness
1,F00002,2025-01-06,B05,HOU002,6,8,no,keep same quality,quick and convenient
2,F00003,2025-01-01,B05,RTE002,7,4,maybe,more flavor options,good value for money
3,F00004,2025-02-16,B01,BEV002,10,6,yes,keep same quality,liked the freshness
4,F00005,2025-01-29,B02,HOU001,4,6,yes,freshness issue,quality felt inconsistent

### Findings

- transaction_ts is stored as object and should be converted to datetime.
- sales_date is stored as object and should be converted to datetime.
- Identifier columns (transaction_id, branch_id, customer_id) are correctly stored as object.
- basket_amount is stored as integer and requires no type conversion.

In [7]:
for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print("=" * 70)

    print(f"Shape: {df.shape}")
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\n")

======================================================================
Sales
======================================================================
Shape: (5129, 7)

Columns:
['transaction_id', 'transaction_ts', 'sales_date', 'branch_id', 'customer_id', 'payment_method', 'basket_amount']

Data Types:
transaction_id    object
transaction_ts    object
sales_date        object
branch_id         object
customer_id       object
payment_method    object
basket_amount      int64
dtype: object

First 5 Rows:

,transaction_id,transaction_ts,sales_date,branch_id,customer_id,payment_method,basket_amount
0,T0000001,2025-01-01 10:34:15,2025-01-01,B02,C0086,cash,7200
1,T0000002,2025-01-01 18:31:46,2025-01-01,B01,C0026,wallet,14300
2,T0000003,2025-01-01 11:05:56,2025-01-01,B02,C0039,card,4800
3,T0000004,2025-01-01 07:02:00,2025-01-01,B05,NaN,card,18700
4,T0000005,2025-01-01 07:44:34,2025-01-01,B04,C0055,wallet,19800

======================================================================
Sales Line
======================================================================
Shape: (12914, 7)

Columns:
['line_id', 'transaction_id', 'product_code', 'qty', 'unit_price', 'discount_amt', 'line_amount']

Data Types:
line_id           object
transaction_id    object
product_code      object
qty                int64
unit_price         int64
discount_amt       int64
line_amount        int64
dtype: object

First 5 Rows:

,line_id,transaction_id,product_code,qty,unit_price,discount_amt,line_amount
0,L00000001,T0000001,BEV003,1,4000,200,3800
1,L00000002,T0000001,DES003,1,3700,300,3400
2,L00000003,T0000002,BEV002,1,1600,300,1300
3,L00000004,T0000002,DES003,1,3500,300,3200
4,L00000005,T0000002,BEV003,1,4200,300,3900

======================================================================
Products
======================================================================
Shape: (18, 7)

Columns:
['product_code', 'product_name', 'category_code', 'category_name', 'base_price', 'brand_type', 'margin_band']

Data Types:
product_code     object
product_name     object
category_code    object
category_name    object
base_price        int64
brand_type       object
margin_band      object
dtype: object

First 5 Rows:

,product_code,product_name,category_code,category_name,base_price,brand_type,margin_band
0,SNK001,Potato Chips Sea Salt,SNK,Snacks,3800,Import,A
1,SNK002,Corn Chips Spicy,SNK,Snacks,4200,Import,C
2,SNK003,Protein Bar,SNK,Snacks,5200,Local,A
3,SNK004,Chocolate Wafer,SNK,Snacks,2800,Local,B
4,BEV001,Cola 500ml,BEV,Beverage,2500,Local,C

======================================================================
Customers
======================================================================
Shape: (120, 6)

Columns:
['customer_id', 'join_date', 'seed_segment', 'gender', 'age', 'loyalty_channel']

Data Types:
customer_id        object
join_date          object
seed_segment       object
gender             object
age                 int64
loyalty_channel    object
dtype: object

First 5 Rows:

  customer_id   join_date          seed_segment gender  age loyalty_channel
0       C0001  2024-05-31      Morning commuter      F   41             App
1       C0002  2023-05-22      Morning commuter      F   31            Card
2       C0003  2023-06-07  Student value seeker      M   47     Cash-linked
3       C0004  2023-08-26       Family stock-up      M   33             App
4       C0005  2024-03-28      Morning commuter      M   51            Card

======================================================================
Branches
======================================================================
Shape: (6, 4)

Columns:
['branch_id', 'branch_name', 'zone', 'store_size']

Data Types:
branch_id      object
branch_name    object
zone           object
store_size     object
dtype: object

First 5 Rows:

  branch_id branch_name              zone store_size
0       B01    Branch 1          Downtown     Medium
1       B02    Branch 2   Office district     Medium
2       B03    Branch 3  Residential east      Small
3       B04    Branch 4  Residential west      Small
4       B05    Branch 5        University      Small

======================================================================
Inventory
======================================================================
Shape: (4320, 6)

Columns:
['inventory_date', 'branch_id', 'product_code', 'on_hand_qty', 'reorder_point', 'stock_flag']

Data Types:
inventory_date    object
branch_id         object
product_code      object
on_hand_qty        int64
reorder_point      int64
stock_flag        object
dtype: object

First 5 Rows:

  inventory_date branch_id product_code  on_hand_qty  reorder_point stock_flag
0     2025-01-01       B01       SNK004           29             36         OK
1     2025-01-01       B01       DES003           22             26        LOW
2     2025-01-01       B01       SNK002            1              5        OOS
3     2025-01-01       B01       SNK003           11             18         OK
4     2025-01-01       B01       SNK001           14             20         OK

======================================================================
Survey
======================================================================
Shape: (900, 9)

Columns:
['feedback_id', 'feedback_date', 'branch_id', 'product_code', 'quality_score', 'visual_score', 'would_buy_again', 'what_to_improve', 'general_thoughts']

Data Types:
feedback_id         object
feedback_date       object
branch_id           object
product_code        object
quality_score        int64
visual_score         int64
would_buy_again     object
what_to_improve     object
general_thoughts    object
dtype: object

First 5 Rows:

,feedback_id,feedback_date,branch_id,product_code,quality_score,visual_score,would_buy_again,what_to_improve,general_thoughts
0,F00001,2025-01-27,B01,RTE002,7,7,yes,bundle with drink,liked the freshness
1,F00002,2025-01-06,B05,HOU002,6,8,no,keep same quality,quick and convenient
2,F00003,2025-01-01,B05,RTE002,7,4,maybe,more flavor options,good value for money
3,F00004,2025-02-16,B01,BEV002,10,6,yes,keep same quality,liked the freshness
4,F00005,2025-01-29,B02,HOU001,4,6,yes,freshness issue,quality felt inconsistent

In [8]:
print(f"Shape: {products.shape}")
print("\nColumns:")
print(products.columns.tolist())
print("\nData Types:")
print(products.dtypes)
print("\nFirst 5 Rows:")
display(products.head())

Shape: (18, 7)

Columns:
['product_code', 'product_name', 'category_code', 'category_name', 'base_price', 'brand_type', 'margin_band']

Data Types:
product_code     object
product_name     object
category_code    object
category_name    object
base_price        int64
brand_type       object
margin_band      object
dtype: object

First 5 Rows:

,product_code,product_name,category_code,category_name,base_price,brand_type,margin_band
0,SNK001,Potato Chips Sea Salt,SNK,Snacks,3800,Import,A
1,SNK002,Corn Chips Spicy,SNK,Snacks,4200,Import,C
2,SNK003,Protein Bar,SNK,Snacks,5200,Local,A
3,SNK004,Chocolate Wafer,SNK,Snacks,2800,Local,B
4,BEV001,Cola 500ml,BEV,Beverage,2500,Local,C

In [9]:
print(f"Shape: {customers.shape}")
print("\nColumns:")
print(customers.columns.tolist())
print("\nData Types:")
print(customers.dtypes)
print("\nFirst 5 Rows:")
display(customers.head())

Shape: (120, 6)

Columns:
['customer_id', 'join_date', 'seed_segment', 'gender', 'age', 'loyalty_channel']

Data Types:
customer_id        object
join_date          object
seed_segment       object
gender             object
age                 int64
loyalty_channel    object
dtype: object

First 5 Rows:

  customer_id   join_date          seed_segment gender  age loyalty_channel
0       C0001  2024-05-31      Morning commuter      F   41             App
1       C0002  2023-05-22      Morning commuter      F   31            Card
2       C0003  2023-06-07  Student value seeker      M   47     Cash-linked
3       C0004  2023-08-26       Family stock-up      M   33             App
4       C0005  2024-03-28      Morning commuter      M   51            Card

In [10]:
print(f"Shape: {branches.shape}")
print("\nColumns:")
print(branches.columns.tolist())
print("\nData Types:")
print(branches.dtypes)
print("\nFirst 5 Rows:")
display(branches.head())

Shape: (6, 4)

Columns:
['branch_id', 'branch_name', 'zone', 'store_size']

Data Types:
branch_id      object
branch_name    object
zone           object
store_size     object
dtype: object

First 5 Rows:

  branch_id branch_name              zone store_size
0       B01    Branch 1          Downtown     Medium
1       B02    Branch 2   Office district     Medium
2       B03    Branch 3  Residential east      Small
3       B04    Branch 4  Residential west      Small
4       B05    Branch 5        University      Small

In [11]:
print(f"Shape: {inventory.shape}")
print("\nColumns:")
print(inventory.columns.tolist())
print("\nData Types:")
print(inventory.dtypes)
print("\nFirst 5 Rows:")
display(inventory.head())

Shape: (4320, 6)

Columns:
['inventory_date', 'branch_id', 'product_code', 'on_hand_qty', 'reorder_point', 'stock_flag']

Data Types:
inventory_date    object
branch_id         object
product_code      object
on_hand_qty        int64
reorder_point      int64
stock_flag        object
dtype: object

First 5 Rows:

  inventory_date branch_id product_code  on_hand_qty  reorder_point stock_flag
0     2025-01-01       B01       SNK004           29             36         OK
1     2025-01-01       B01       DES003           22             26        LOW
2     2025-01-01       B01       SNK002            1              5        OOS
3     2025-01-01       B01       SNK003           11             18         OK
4     2025-01-01       B01       SNK001           14             20         OK

In [12]:
print(f"Shape: {survey.shape}")
print("\nColumns:")
print(survey.columns.tolist())
print("\nData Types:")
print(survey.dtypes)
print("\nFirst 5 Rows:")
display(survey.head())

Shape: (900, 9)

Columns:
['feedback_id', 'feedback_date', 'branch_id', 'product_code', 'quality_score', 'visual_score', 'would_buy_again', 'what_to_improve', 'general_thoughts']

Data Types:
feedback_id         object
feedback_date       object
branch_id           object
product_code        object
quality_score        int64
visual_score         int64
would_buy_again     object
what_to_improve     object
general_thoughts    object
dtype: object

First 5 Rows:

,feedback_id,feedback_date,branch_id,product_code,quality_score,visual_score,would_buy_again,what_to_improve,general_thoughts
0,F00001,2025-01-27,B01,RTE002,7,7,yes,bundle with drink,liked the freshness
1,F00002,2025-01-06,B05,HOU002,6,8,no,keep same quality,quick and convenient
2,F00003,2025-01-01,B05,RTE002,7,4,maybe,more flavor options,good value for money
3,F00004,2025-02-16,B01,BEV002,10,6,yes,keep same quality,liked the freshness
4,F00005,2025-01-29,B02,HOU001,4,6,yes,freshness issue,quality felt inconsistent

## 6. Missing Values

In [13]:
missing_summary = pd.DataFrame(
    {
        name: df.isna().sum()
        for name, df in datasets.items()
    }
)

missing_summary

,Sales,Sales Line,Products,Customers,Branches,Inventory,Survey
age,NaN,NaN,NaN,0.0,NaN,NaN,NaN
base_price,NaN,NaN,0.0,NaN,NaN,NaN,NaN
basket_amount,0.0,NaN,NaN,NaN,NaN,NaN,NaN
branch_id,0.0,NaN,NaN,NaN,0.0,0.0,0.0
branch_name,NaN,NaN,NaN,NaN,0.0,NaN,NaN
brand_type,NaN,NaN,0.0,NaN,NaN,NaN,NaN
category_code,NaN,NaN,0.0,NaN,NaN,NaN,NaN
category_name,NaN,NaN,0.0,NaN,NaN,NaN,NaN
customer_id,856.0,NaN,NaN,0.0,NaN,NaN,NaN
discount_amt,NaN,0.0,NaN,NaN,NaN,NaN,NaN
feedback_date,NaN,NaN,NaN,NaN,NaN,NaN,0.0
feedback_id,NaN,NaN,NaN,NaN,NaN,NaN,0.0
gender,NaN,NaN,NaN,0.0,NaN,NaN,NaN
general_thoughts,NaN,NaN,NaN,NaN,NaN,NaN,0.0
inventory_date,NaN,NaN,NaN,NaN,NaN,0.0,NaN
join_date,NaN,NaN,NaN,0.0,NaN,NaN,NaN
line_amount,NaN,0.0,NaN,NaN,NaN,NaN,NaN
line_id,NaN,0.0,NaN,NaN,NaN,NaN,NaN
loyalty_channel,NaN,NaN,NaN,0.0,NaN,NaN,NaN
margin_band,NaN,NaN,0.0,NaN,NaN,NaN,NaN
on_hand_qty,NaN,NaN,NaN,NaN,NaN,0.0,NaN
payment_method,0.0,NaN,NaN,NaN,NaN,NaN,NaN
product_code,NaN,0.0,0.0,NaN,NaN,0.0,0.0
product_name,NaN,NaN,0.0,NaN,NaN,NaN,NaN
qty,NaN,0.0,NaN,NaN,NaN,NaN,NaN
quality_score,NaN,NaN,NaN,NaN,NaN,NaN,0.0
reorder_point,NaN,NaN,NaN,NaN,NaN,0.0,NaN
sales_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN
seed_segment,NaN,NaN,NaN,0.0,NaN,NaN,NaN
stock_flag,NaN,NaN,NaN,NaN,NaN,0.0,NaN
store_size,NaN,NaN,NaN,NaN,0.0,NaN,NaN
transaction_id,0.0,0.0,NaN,NaN,NaN,NaN,NaN
transaction_ts,0.0,NaN,NaN,NaN,NaN,NaN,NaN
unit_price,NaN,0.0,NaN,NaN,NaN,NaN,NaN
visual_score,NaN,NaN,NaN,NaN,NaN,NaN,0.0
what_to_improve,NaN,NaN,NaN,NaN,NaN,NaN,0.0
would_buy_again,NaN,NaN,NaN,NaN,NaN,NaN,0.0
zone,NaN,NaN,NaN,NaN,0.0,NaN,NaN

In [14]:
missing_pct = pd.DataFrame(
    {
        name: (df.isna().mean() * 100).round(2)
        for name, df in datasets.items()
    }
)

missing_pct

,Sales,Sales Line,Products,Customers,Branches,Inventory,Survey
age,NaN,NaN,NaN,0.0,NaN,NaN,NaN
base_price,NaN,NaN,0.0,NaN,NaN,NaN,NaN
basket_amount,0.00,NaN,NaN,NaN,NaN,NaN,NaN
branch_id,0.00,NaN,NaN,NaN,0.0,0.0,0.0
branch_name,NaN,NaN,NaN,NaN,0.0,NaN,NaN
brand_type,NaN,NaN,0.0,NaN,NaN,NaN,NaN
category_code,NaN,NaN,0.0,NaN,NaN,NaN,NaN
category_name,NaN,NaN,0.0,NaN,NaN,NaN,NaN
customer_id,16.69,NaN,NaN,0.0,NaN,NaN,NaN
discount_amt,NaN,0.0,NaN,NaN,NaN,NaN,NaN
feedback_date,NaN,NaN,NaN,NaN,NaN,NaN,0.0
feedback_id,NaN,NaN,NaN,NaN,NaN,NaN,0.0
gender,NaN,NaN,NaN,0.0,NaN,NaN,NaN
general_thoughts,NaN,NaN,NaN,NaN,NaN,NaN,0.0
inventory_date,NaN,NaN,NaN,NaN,NaN,0.0,NaN
join_date,NaN,NaN,NaN,0.0,NaN,NaN,NaN
line_amount,NaN,0.0,NaN,NaN,NaN,NaN,NaN
line_id,NaN,0.0,NaN,NaN,NaN,NaN,NaN
loyalty_channel,NaN,NaN,NaN,0.0,NaN,NaN,NaN
margin_band,NaN,NaN,0.0,NaN,NaN,NaN,NaN
on_hand_qty,NaN,NaN,NaN,NaN,NaN,0.0,NaN
payment_method,0.00,NaN,NaN,NaN,NaN,NaN,NaN
product_code,NaN,0.0,0.0,NaN,NaN,0.0,0.0
product_name,NaN,NaN,0.0,NaN,NaN,NaN,NaN
qty,NaN,0.0,NaN,NaN,NaN,NaN,NaN
quality_score,NaN,NaN,NaN,NaN,NaN,NaN,0.0
reorder_point,NaN,NaN,NaN,NaN,NaN,0.0,NaN
sales_date,0.00,NaN,NaN,NaN,NaN,NaN,NaN
seed_segment,NaN,NaN,NaN,0.0,NaN,NaN,NaN
stock_flag,NaN,NaN,NaN,NaN,NaN,0.0,NaN
store_size,NaN,NaN,NaN,NaN,0.0,NaN,NaN
transaction_id,0.00,0.0,NaN,NaN,NaN,NaN,NaN
transaction_ts,0.00,NaN,NaN,NaN,NaN,NaN,NaN
unit_price,NaN,0.0,NaN,NaN,NaN,NaN,NaN
visual_score,NaN,NaN,NaN,NaN,NaN,NaN,0.0
what_to_improve,NaN,NaN,NaN,NaN,NaN,NaN,0.0
would_buy_again,NaN,NaN,NaN,NaN,NaN,NaN,0.0
zone,NaN,NaN,NaN,NaN,0.0,NaN,NaN

In [15]:
for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * 40)
    print(df.isna().sum())

Sales
----------------------------------------
transaction_id      0
transaction_ts      0
sales_date          0
branch_id           0
customer_id       856
payment_method      0
basket_amount       0
dtype: int64

Sales Line
----------------------------------------
line_id           0
transaction_id    0
product_code      0
qty               0
unit_price        0
discount_amt      0
line_amount       0
dtype: int64

Products
----------------------------------------
product_code     0
product_name     0
category_code    0
category_name    0
base_price       0
brand_type       0
margin_band      0
dtype: int64

Customers
----------------------------------------
customer_id        0
join_date          0
seed_segment       0
gender             0
age                0
loyalty_channel    0
dtype: int64

Branches
----------------------------------------
branch_id      0
branch_name    0
zone           0
store_size     0
dtype: int64

Inventory
----------------------------------------
inventory_date    0
branch_id         0
product_code      0
on_hand_qty       0
reorder_point     0
stock_flag        0
dtype: int64

Survey
----------------------------------------
feedback_id         0
feedback_date       0
branch_id           0
product_code        0
quality_score       0
visual_score        0
would_buy_again     0
what_to_improve     0
general_thoughts    0
dtype: int64

In [16]:
for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * 40)
    print((df.isna().mean() * 100).round(2))

Sales
----------------------------------------
transaction_id     0.00
transaction_ts     0.00
sales_date         0.00
branch_id          0.00
customer_id       16.69
payment_method     0.00
basket_amount      0.00
dtype: float64

Sales Line
----------------------------------------
line_id           0.0
transaction_id    0.0
product_code      0.0
qty               0.0
unit_price        0.0
discount_amt      0.0
line_amount       0.0
dtype: float64

Products
----------------------------------------
product_code     0.0
product_name     0.0
category_code    0.0
category_name    0.0
base_price       0.0
brand_type       0.0
margin_band      0.0
dtype: float64

Customers
----------------------------------------
customer_id        0.0
join_date          0.0
seed_segment       0.0
gender             0.0
age                0.0
loyalty_channel    0.0
dtype: float64

Branches
----------------------------------------
branch_id      0.0
branch_name    0.0
zone           0.0
store_size     0.0
dtype: float64

Inventory
----------------------------------------
inventory_date    0.0
branch_id         0.0
product_code      0.0
on_hand_qty       0.0
reorder_point     0.0
stock_flag        0.0
dtype: float64

Survey
----------------------------------------
feedback_id         0.0
feedback_date       0.0
branch_id           0.0
product_code        0.0
quality_score       0.0
visual_score        0.0
would_buy_again     0.0
what_to_improve     0.0
general_thoughts    0.0
dtype: float64

## 7. Duplicate Check

In [17]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

Sales: 0 duplicate rows
Sales Line: 0 duplicate rows
Products: 0 duplicate rows
Customers: 0 duplicate rows
Branches: 0 duplicate rows
Inventory: 0 duplicate rows
Survey: 0 duplicate rows

## 7. Duplicate Check
### Key-level Duplicate Check

In [18]:
key_checks = {
    "Sales": ["transaction_id"],
    "Sales Line": ["line_id"],
    "Products": ["product_code"],
    "Customers": ["customer_id"],
    "Branches": ["branch_id"],
    "Inventory": ["inventory_date", "branch_id", "product_code"],
    "Survey": ["feedback_id"],
}

for name, keys in key_checks.items():
    df = datasets[name]
    duplicates = df.duplicated(subset=keys).sum()
    
    print(f"{name}: {duplicates} duplicate key rows")

Sales: 0 duplicate key rows
Sales Line: 0 duplicate key rows
Products: 0 duplicate key rows
Customers: 0 duplicate key rows
Branches: 0 duplicate key rows
Inventory: 0 duplicate key rows
Survey: 0 duplicate key rows

## 8. Invalid Values

In [19]:
print("Sales - basket_amount")
print("Negative:", (sales["basket_amount"] < 0).sum())
print("Zero:", (sales["basket_amount"] == 0).sum())

Sales - basket_amount
Negative: 0
Zero: 0

In [20]:
print("Sales Line - qty")
print("Negative:", (sales_line["qty"] < 0).sum())
print("Zero:", (sales_line["qty"] == 0).sum())

print("\nSales Line - unit_price")
print("Negative:", (sales_line["unit_price"] < 0).sum())
print("Zero:", (sales_line["unit_price"] == 0).sum())

print("\nSales Line - discount_amt")
print("Negative:", (sales_line["discount_amt"] < 0).sum())

print("\nSales Line - line_amount")
print("Negative:", (sales_line["line_amount"] < 0).sum())

Sales Line - qty
Negative: 0
Zero: 0

Sales Line - unit_price
Negative: 0
Zero: 0

Sales Line - discount_amt
Negative: 0

Sales Line - line_amount
Negative: 0

In [21]:
print("Products - base_price")
print("Negative:", (products["base_price"] < 0).sum())
print("Zero:", (products["base_price"] == 0).sum())

Products - base_price
Negative: 0
Zero: 0

In [22]:
print("Customers - age")
print("Below 0:", (customers["age"] < 0).sum())
print("Above 100:", (customers["age"] > 100).sum())

Customers - age
Below 0: 0
Above 100: 0

In [23]:
print("Inventory - on_hand_qty")
print("Negative:", (inventory["on_hand_qty"] < 0).sum())

print("\nInventory - reorder_point")
print("Negative:", (inventory["reorder_point"] < 0).sum())

Inventory - on_hand_qty
Negative: 0

Inventory - reorder_point
Negative: 0

In [24]:
print("Survey - quality_score")
print("Below 0:", (survey["quality_score"] < 0).sum())

print("\nSurvey - visual_score")
print("Below 0:", (survey["visual_score"] < 0).sum())

Survey - quality_score
Below 0: 0

Survey - visual_score
Below 0: 0

In [25]:
checks = {
    "Sales → Customers": (
        sales["customer_id"].dropna(),
        customers["customer_id"]
    ),
    "Sales → Branches": (
        sales["branch_id"],
        branches["branch_id"]
    ),
    "Sales Line → Sales": (
        sales_line["transaction_id"],
        sales["transaction_id"]
    ),
    "Sales Line → Products": (
        sales_line["product_code"],
        products["product_code"]
    ),
    "Inventory → Branches": (
        inventory["branch_id"],
        branches["branch_id"]
    ),
    "Inventory → Products": (
        inventory["product_code"],
        products["product_code"]
    ),
    "Survey → Branches": (
        survey["branch_id"],
        branches["branch_id"]
    ),
    "Survey → Products": (
        survey["product_code"],
        products["product_code"]
    ),
}

for name, (child, parent) in checks.items():
    unmatched = (~child.isin(parent)).sum()
    print(f"{name}: {unmatched} unmatched")

Sales → Customers: 0 unmatched
Sales → Branches: 0 unmatched
Sales Line → Sales: 0 unmatched
Sales Line → Products: 0 unmatched
Inventory → Branches: 0 unmatched
Inventory → Products: 0 unmatched
Survey → Branches: 0 unmatched
Survey → Products: 0 unmatched

In [26]:
transaction_totals = (
    sales_line
    .groupby("transaction_id")["line_amount"]
    .sum()
    .rename("calculated_amount")
)

sales_check = sales.merge(
    transaction_totals,
    on="transaction_id",
    how="left"
)

sales_check["difference"] = (
    sales_check["basket_amount"] -
    sales_check["calculated_amount"]
)

print("Transactions:", len(sales_check))
print("Exact matches:", (sales_check["difference"] == 0).sum())
print("Non-zero differences:", (sales_check["difference"] != 0).sum())

Transactions: 5129
Exact matches: 5129
Non-zero differences: 0

In [27]:
sales_line_check = sales_line.copy()

sales_line_check["calculated_amount"] = (
    sales_line_check["qty"] * sales_line_check["unit_price"]
    - sales_line_check["discount_amt"]
)

sales_line_check["difference"] = (
    sales_line_check["line_amount"]
    - sales_line_check["calculated_amount"]
)

print("Sales lines:", len(sales_line_check))
print("Exact matches:", (sales_line_check["difference"] == 0).sum())
print("Non-zero differences:", (sales_line_check["difference"] != 0).sum())

Sales lines: 12914
Exact matches: 12914
Non-zero differences: 0

In [28]:
date_columns = {
    "Sales - transaction_ts": sales["transaction_ts"],
    "Sales - sales_date": sales["sales_date"],
    "Customers - join_date": customers["join_date"],
    "Inventory - inventory_date": inventory["inventory_date"],
    "Survey - feedback_date": survey["feedback_date"],
}

for name, col in date_columns.items():
    parsed = pd.to_datetime(col, errors="coerce")
    invalid = parsed.isna().sum()
    
    print(f"{name}: {invalid} invalid dates")

Sales - transaction_ts: 0 invalid dates
Sales - sales_date: 0 invalid dates
Customers - join_date: 0 invalid dates
Inventory - inventory_date: 0 invalid dates
Survey - feedback_date: 0 invalid dates

## 9. Datetime Conversion

In [29]:
sales["transaction_ts"] = pd.to_datetime(sales["transaction_ts"])
sales["sales_date"] = pd.to_datetime(sales["sales_date"])

customers["join_date"] = pd.to_datetime(customers["join_date"])

inventory["inventory_date"] = pd.to_datetime(inventory["inventory_date"])

survey["feedback_date"] = pd.to_datetime(survey["feedback_date"])

In [30]:
date_columns = {
    "Sales - transaction_ts": sales["transaction_ts"],
    "Sales - sales_date": sales["sales_date"],
    "Customers - join_date": customers["join_date"],
    "Inventory - inventory_date": inventory["inventory_date"],
    "Survey - feedback_date": survey["feedback_date"],
}

for name, col in date_columns.items():
    print(f"{name}: {col.dtype}")

Sales - transaction_ts: datetime64[ns]
Sales - sales_date: datetime64[ns]
Customers - join_date: datetime64[ns]
Inventory - inventory_date: datetime64[ns]
Survey - feedback_date: datetime64[ns]

In [31]:
inventory_check = inventory.copy()

inventory_check["expected_flag"] = np.select(
    [
        inventory_check["on_hand_qty"] == 0,
        inventory_check["on_hand_qty"] <= inventory_check["reorder_point"]
    ],
    [
        "OOS",
        "LOW"
    ],
    default="OK"
)

print(
    "Flag mismatches:",
    (inventory_check["stock_flag"] != inventory_check["expected_flag"]).sum()
)

Flag mismatches: 2804

In [32]:
inventory_check[
    ["on_hand_qty", "reorder_point", "stock_flag", "expected_flag"]
].value_counts().head(15)

on_hand_qty  reorder_point  stock_flag  expected_flag
22           26             OK          LOW              25
18           24             OK          LOW              24
14           20             OK          LOW              24
18           23             OK          LOW              24
             21             OK          LOW              23
19           23             OK          LOW              22
14           18             OK          LOW              22
17           23             OK          LOW              21
16           19             OK          LOW              21
20           24             LOW         LOW              20
10           14             OK          LOW              19
15           21             OK          LOW              19
18           20             OK          LOW              19
21           26             OK          LOW              19
13           18             OK          LOW              19
Name: count, dtype: int64

In [33]:
inventory_check[
    inventory_check["stock_flag"] != inventory_check["expected_flag"]
][["on_hand_qty", "reorder_point", "stock_flag", "expected_flag"]].head(20)

    on_hand_qty  reorder_point stock_flag expected_flag
0            29             36         OK           LOW
2             1              5        OOS           LOW
3            11             18         OK           LOW
4            14             20         OK           LOW
6            22             29         OK           LOW
7            23             29         OK           LOW
9            22             26         OK           LOW
10           23             26         OK           LOW
12           34             42         OK           LOW
13           21             24         OK           LOW
14           21             23         OK           LOW
16           12             21         OK           LOW
19            5              8         OK           LOW
21           18             18         OK           LOW
23           24             31         OK           LOW
27           14             20         OK           LOW
28           26             32         OK           LOW
29            9             12         OK           LOW
30           26             30         OK           LOW
31           12             16         OK           LOW

In [34]:
inventory["stock_flag"].value_counts()

stock_flag
OK     2819
LOW    1458
OOS      43
Name: count, dtype: int64

In [35]:
inventory_check["stock_ratio"] = (
    inventory_check["on_hand_qty"] /
    inventory_check["reorder_point"]
)

inventory_check.groupby("stock_flag")["stock_ratio"].describe()

c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

             count      mean       std  min       25%       50%       75%  max
stock_flag
LOW         1456.0       inf       NaN  0.0  0.692308  0.794495  0.869565  inf
OK          2815.0  0.782266  0.191524  0.0  0.700000  0.800000  0.880000  3.0
OOS           42.0       inf       NaN  0.0  0.000000  0.133929  0.276786  inf

In [36]:
for flag in inventory["stock_flag"].unique():
    print(f"\n--- {flag} ---")
    display(
        inventory_check[
            inventory_check["stock_flag"] == flag
        ][["on_hand_qty", "reorder_point", "stock_ratio"]]
        .head(10)
    )

--- OK ---

    on_hand_qty  reorder_point  stock_ratio
0            29             36     0.805556
3            11             18     0.611111
4            14             20     0.700000
6            22             29     0.758621
7            23             29     0.793103
8            18             17     1.058824
9            22             26     0.846154
10           23             26     0.884615
12           34             42     0.809524
13           21             24     0.875000

--- LOW ---

    on_hand_qty  reorder_point  stock_ratio
1            22             26     0.846154
5            14             16     0.875000
11           25             31     0.806452
15           18             25     0.720000
17           28             29     0.965517
18            4             12     0.333333
20           25             28     0.892857
24           16             23     0.695652
25           24             28     0.857143
26           18             26     0.692308

--- OOS ---

     on_hand_qty  reorder_point  stock_ratio
2              1              5         0.20
22             0              5         0.00
148            1              2         0.50
239            2              8         0.25
269            1              1         1.00
322            0              4         0.00
454            0              8         0.00
553            0              3         0.00
599            0              2         0.00
704            0              2         0.00

In [37]:
print("reorder_point = 0:", (inventory["reorder_point"] == 0).sum())
print("reorder_point < 0:", (inventory["reorder_point"] < 0).sum())

reorder_point = 0: 10
reorder_point < 0: 0

In [38]:
inventory.groupby("stock_flag")[["on_hand_qty", "reorder_point"]].agg(
    ["min", "median", "max"]
)

           on_hand_qty            reorder_point
                   min median max           min median max
stock_flag
LOW                  0   18.0  52             0   22.0  53
OK                   0   18.0  48             0   22.0  55
OOS                  0    1.0   2             0    5.0  13

In [39]:
inventory[
    inventory["reorder_point"] == 0
][
    ["inventory_date", "branch_id", "product_code",
     "on_hand_qty", "reorder_point", "stock_flag"]
]

,inventory_date,branch_id,product_code,on_hand_qty,reorder_point,stock_flag
426,2025-01-09,B06,HOU002,0,0,OK
1041,2025-01-22,B05,DES002,0,0,LOW
1220,2025-01-26,B03,DES002,1,0,LOW
2448,2025-02-21,B01,SNK002,0,0,OK
2499,2025-02-22,B01,BEV004,0,0,OOS
2765,2025-02-27,B04,HOU002,1,0,LOW
2927,2025-03-02,B06,SNK003,0,0,OK
3790,2025-03-20,B06,BEV004,1,0,OOS
3957,2025-03-24,B03,BEV003,0,0,OK
4225,2025-03-30,B01,DES003,0,0,LOW

In [40]:
inventory.groupby("stock_flag")[["on_hand_qty", "reorder_point"]].agg(
    min=("on_hand_qty", "min"),
    median=("on_hand_qty", "median"),
    max=("on_hand_qty", "max")
)

            min  median  max
stock_flag
LOW           0    18.0   52
OK            0    18.0   48
OOS           0     1.0    2

In [41]:
zero_reorder = inventory[
    inventory["reorder_point"] == 0
][[
    "inventory_date",
    "branch_id",
    "product_code",
    "on_hand_qty",
    "reorder_point",
    "stock_flag"
]]

print(zero_reorder.to_string(index=False))

inventory_date branch_id product_code  on_hand_qty  reorder_point stock_flag
    2025-01-09       B06       HOU002            0              0         OK
    2025-01-22       B05       DES002            0              0        LOW
    2025-01-26       B03       DES002            1              0        LOW
    2025-02-21       B01       SNK002            0              0         OK
    2025-02-22       B01       BEV004            0              0        OOS
    2025-02-27       B04       HOU002            1              0        LOW
    2025-03-02       B06       SNK003            0              0         OK
    2025-03-20       B06       BEV004            1              0        OOS
    2025-03-24       B03       BEV003            0              0         OK
    2025-03-30       B01       DES003            0              0        LOW

In [42]:
flag_summary = inventory.groupby("stock_flag")[[
    "on_hand_qty",
    "reorder_point"
]].agg(["min", "median", "max"])

print(flag_summary.to_string())

           on_hand_qty            reorder_point
                   min median max           min median max
stock_flag
LOW                  0   18.0  52             0   22.0  53
OK                   0   18.0  48             0   22.0  55
OOS                  0    1.0   2             0    5.0  13

### Inventory Flag

`stock_flag` was reviewed against `on_hand_qty` and `reorder_point`.
No single deterministic rule was identified, so the original `stock_flag` values were retained.

In [43]:
print("Quality score:")
print(survey["quality_score"].value_counts().sort_index())

print("\nVisual score:")
print(survey["visual_score"].value_counts().sort_index())

Quality score:
quality_score
2       1
3       7
4      38
5     141
6     214
7     220
8     182
9      72
10     25
Name: count, dtype: int64

Visual score:
visual_score
1       1
2       4
3      20
4      68
5     139
6     228
7     212
8     137
9      71
10     20
Name: count, dtype: int64

In [44]:
print("Would buy again:")
print(survey["would_buy_again"].value_counts())

print("\nGender:")
print(customers["gender"].value_counts())

print("\nLoyalty channel:")
print(customers["loyalty_channel"].value_counts())

print("\nPayment method:")
print(sales["payment_method"].value_counts())

Would buy again:
would_buy_again
yes      394
no       274
maybe    232
Name: count, dtype: int64

Gender:
gender
M    64
F    56
Name: count, dtype: int64

Loyalty channel:
loyalty_channel
App            45
Cash-linked    41
Card           34
Name: count, dtype: int64

Payment method:
payment_method
card      1724
cash      1707
wallet    1698
Name: count, dtype: int64

In [45]:
numeric_columns = {
    "Sales": ["basket_amount"],
    "Sales Line": ["qty", "unit_price", "discount_amt", "line_amount"],
    "Products": ["base_price"],
    "Customers": ["age"],
    "Inventory": ["on_hand_qty", "reorder_point"],
    "Survey": ["quality_score", "visual_score"],
}

for name, columns in numeric_columns.items():
    print(f"\n{name}")
    print(df := datasets[name][columns].describe().round(2).to_string())

Sales
       basket_amount
count        5129.00
mean        13490.72
std          8654.61
min          1300.00
25%          6800.00
50%         11700.00
75%         18300.00
max         66200.00

Sales Line
            qty  unit_price  discount_amt  line_amount
count  12914.00    12914.00      12914.00     12914.00
mean       1.25     4415.87        166.53      5358.05
std        0.51     1915.81        188.52      3407.36
min        1.00     1600.00          0.00      1100.00
25%        1.00     2800.00          0.00      2900.00
50%        1.00     4000.00          0.00      4500.00
75%        1.00     5900.00        300.00      6700.00
max        3.00     8800.00        500.00     26200.00

Products
       base_price
count       18.00
mean      4377.78
std       1954.65
min       1800.00
25%       2825.00
50%       4000.00
75%       5725.00
max       8600.00

Customers
          age
count  120.00
mean    36.32
std     11.10
min     18.00
25%     26.00
50%     36.00
75%     47.00
max     55.00

Inventory
       on_hand_qty  reorder_point
count      4320.00        4320.00
mean         17.52          22.09
std           7.91           8.48
min           0.00           0.00
25%          12.00          16.00
50%          18.00          22.00
75%          23.00          28.00
max          52.00          55.00

Survey
       quality_score  visual_score
count         900.00        900.00
mean            6.73          6.47
std             1.45          1.56
min             2.00          1.00
25%             6.00          5.00
50%             7.00          6.00
75%             8.00          8.00
max            10.00         10.00

In [46]:
sales["transaction_ts"] = pd.to_datetime(sales["transaction_ts"])
sales["sales_date"] = pd.to_datetime(sales["sales_date"])

customers["join_date"] = pd.to_datetime(customers["join_date"])

inventory["inventory_date"] = pd.to_datetime(inventory["inventory_date"])

survey["feedback_date"] = pd.to_datetime(survey["feedback_date"])

In [47]:
from pathlib import Path

CLEAN_DIR = Path("../data/cleaned")
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

In [48]:
cleaned_datasets = {
    "sales_transaction": sales,
    "sales_transactionline": sales_line,
    "product_master": products,
    "customers": customers,
    "branch_master": branches,
    "inventory_daily": inventory,
    "survey_feedback": survey,
}

for name, df in cleaned_datasets.items():
    df.to_csv(CLEAN_DIR / f"{name}.csv", index=False)

## 10. Final Validation

In [49]:
cleaned = {
    name: pd.read_csv(CLEAN_DIR / f"{name}.csv")
    for name in cleaned_datasets
}

In [50]:
for name in cleaned_datasets:
    print(
        f"{name}: "
        f"raw={len(cleaned_datasets[name])}, "
        f"cleaned={len(cleaned[name])}"
    )

sales_transaction: raw=5129, cleaned=5129
sales_transactionline: raw=12914, cleaned=12914
product_master: raw=18, cleaned=18
customers: raw=120, cleaned=120
branch_master: raw=6, cleaned=6
inventory_daily: raw=4320, cleaned=4320
survey_feedback: raw=900, cleaned=900

In [52]:
for name, keys in key_checks.items():
    duplicates = cleaned[name].duplicated(subset=keys).sum()
    print(f"{name}: {duplicates} duplicate key rows")

KeyError: 'Sales'

In [53]:
for name, df in cleaned.items():
    missing = df.isna().sum()
    missing = missing[missing > 0]

    print(f"\n{name}")
    print(missing if len(missing) else "No missing values")

sales_transaction
customer_id    856
dtype: int64

sales_transactionline
No missing values

product_master
No missing values

customers
No missing values

branch_master
No missing values

inventory_daily
No missing values

survey_feedback
No missing values

In [54]:
cleaned_key_checks = {
    "sales_transaction": ["transaction_id"],
    "sales_transactionline": ["line_id"],
    "product_master": ["product_code"],
    "customers": ["customer_id"],
    "branch_master": ["branch_id"],
    "inventory_daily": ["inventory_date", "branch_id", "product_code"],
    "survey_feedback": ["feedback_id"],
}

for name, keys in cleaned_key_checks.items():
    duplicates = cleaned[name].duplicated(subset=keys).sum()
    print(f"{name}: {duplicates} duplicate key rows")

sales_transaction: 0 duplicate key rows
sales_transactionline: 0 duplicate key rows
product_master: 0 duplicate key rows
customers: 0 duplicate key rows
branch_master: 0 duplicate key rows
inventory_daily: 0 duplicate key rows
survey_feedback: 0 duplicate key rows

## Cleaning Summary

- Converted date columns to datetime.
- No duplicate rows or duplicate keys were found.
- No invalid numeric values were identified.
- Referential integrity checks passed.
- Sales and line-level amount calculations were consistent.
- Missing `customer_id` values were retained as valid unknown customers.
- Original `stock_flag` values were retained.
- Cleaned datasets were saved to `data/cleaned/`.